import { ConnectButton } from '@rainbow-me/rainbowkit'
import { ethers } from 'ethers'
import { NextPage } from 'next'
import Head from 'next/head'
import MeowForm from '../components/MeowForm'
import MeowList from '../components/MeowList'
import styles from '../styles/Home.module.css'
import MeowAbi from '../contracts/MeowAbi.json'
import { useEffect, useState } from 'react'
import { createTheme, ThemeProvider } from '@mui/material/styles'
import { orange } from '@mui/material/colors'
import { Alert, Typography } from '@mui/material'

const theme = createTheme({
  palette: {
    primary: {
      main: orange[500]
    },
    secondary: {
      main: '#f44336'
    }
  }
})

const Home: NextPage = () => {
  const [provider, setProvider] = useState(null)
  const contractAddress: string = '0xd054e5724d7d595b72abbb0c460e0221cd859c8f'
  const [error, setError] = useState<string>('')

  useEffect(() => {
    try {
      const provider: ethers.providers.Web3Provider = new ethers.providers.Web3Provider(
        window.ethereum
      )
      setProvider(provider)
    } catch (err) {
      console.error(err)
      if (typeof err === 'string') {
        setError(err)
      } else if (err instanceof Error) {
        setError(err.message)
      }
    }
  }, [])

  return (
    <ThemeProvider theme={theme}>
      <div className={styles.container}>
        <Head>
          <title>RainbowKit App</title>
          <meta
            name='description'
            content='Generated by @rainbow-me/create-rainbowkit'
          />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <ConnectButton />
          <Typography variant='h3' color='primary'>
            Meows
          </Typography>
          {error && (
            <Alert severity='error'>
              <>
                This is an error alert — check it out: <br />
                {{ error }}
              </>
            </Alert>
          )}
          {provider !== null && (
            <>
              <MeowForm
                contractAddress={contractAddress}
                provider={provider}
                meowAbi={MeowAbi}
              />
              <MeowList
                contractAddress={contractAddress}
                provider={provider}
                meowAbi={MeowAbi}
              />
            </>
          )}

          {/* <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://rainbowkit.com" className={styles.card}>
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a href="https://wagmi.sh" className={styles.card}>
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
            className={styles.card}
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
        </main>

        {/* <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer> */}
      </div>
    </ThemeProvider>
  )
}

export default Home
